server:
  port: 80
eureka: 
  client:     # 客户端进行Eureka注册配置
    register-with-eureka: false       # 当前服务不注册到eureka中
    service-url:   
      defaultZone: http://admin:caxinsjava@localhost:7001/eureka,http://admin:caxinsjava@localhost:7002/eureka,http://admin:caxinsjava@localhost:7003/eureka
