server:
  port: 9501
spring:
  application: 
    name: microcloud-zuul-gateway  
security:
  basic:
    enabled: true
  user: 
    name: zdmin
    password: caxinsjava 
eureka: 
  client:     # 客户端进行Eureka注册配置
    service-url:   
      defaultZone: http://admin:caxinsjava@localhost:7001/eureka,http://admin:caxinsjava@localhost:7002/eureka,http://admin:caxinsjava@localhost:7003/eureka
  instance: 
    lease-renewal-interval-in-seconds: 2    # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5    # 如果现在超过了5秒（上一次发送心跳后到等待下一次发送心跳的间隔时间）的间隔（默认是90秒），则认为该服务已经宕机了
    instance-id: gateway-9501.com      # 在信息列表中显示主机名称  
    prefer-ip-address: true        # 访问的路径变为IP地址
info: 
  app.name: nevergiveup
  company.name: com.caxins
  build.artifactId: $project.artifactId$
  bulid.version: $project.version$
zuul:
  AuthorizedRequestFilter:    # 禁用过滤器，设置成true就表示过滤器禁用。但此方法不推荐使用   
    pre: 
      disable: false
  prefix: /caxins-proxy
  ignored-services:
    "*"
  routes:
    microcloud-provider-company: /company-proxy/**
    microcloud-provider-dept: /dept-proxy/**
