server:
  port: 80
logging:
  level:
    cn.mldn.service: DEBUG
feign:
  compression:
    request:
      mime-types:     # 可被压缩的类型
      - text/xml
      - application/xml
      - application/json
      min-request-size: 2048    # 超过2048字节进行压缩
  hystrix: 
    enabled: true
eureka: 
  client:     # 客户端进行Eureka注册配置
    register-with-eureka: false       # 当前服务不注册到eureka中
    service-url:   
      defaultZone: http://admin:caxinsjava@localhost:7001/eureka,http://admin:caxinsjava@localhost:7002/eureka,http://admin:caxinsjava@localhost:7003/eureka
