












































server:
  port: 7001
eureka: 
  server: 
    eviction-interval-timer-in-ms: 600000    # 设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false   # 设置为false表示关闭保护模式
  client: 
    service-url: 
      defaultZone: http://admin:caxinsjava@localhost:7002/eureka,http://admin:caxinsjava@localhost:7003/eureka
    register-with-eureka: false    # 当前的微服务不注册到eureka中
    fetch-registry: false   # 不通过eureka获取注册信息
  instance:  # 定义Eureka实例所在的主机名称
    hostname: eureka-7001.com   # 定义Eureka实例所在的主机名称
security:
  basic:
    enabled: true      # 启用安全认证处理
  user:
    name: admin          # 用户名
    password: caxinsjava     # 密码
  